//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceExam.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedback
    {
        public int IDFeedback { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> Mark { get; set; }
        public string TextFeedback { get; set; }
    
        public virtual TypeService TypeService { get; set; }
    }
}
